spring:
  application:
    name: spring_boot_assignment
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/ipl_matches
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      SASL_MECHANISM: PLAIN
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    data:
      redis:
        host: localhost
        port: 6379
server:
  port: 8088
